"""initial_schema

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("actor_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("old_ref", sa.Text(), nullable=True),
        sa.Column("new_ref", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index(
        "ix_audit_entity",
        "audit_event",
        ["tenant_id", "entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "background_job",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=True),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "next_run_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'running' AND lease_until IS NOT NULL AND lease_token IS NOT NULL) "
            "OR (status <> 'running' AND lease_until IS NULL AND lease_token IS NULL)",
            name=op.f("ck_background_job_lease_state"),
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','succeeded','failed')",
            name=op.f("ck_background_job_status"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_background_job_attempts")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_job")),
        sa.UniqueConstraint(
            "tenant_id", "dedupe_key", name=op.f("uq_background_job_tenant_id_dedupe_key")
        ),
    )
    op.create_index("ix_job_expired", "background_job", ["status", "lease_until"], unique=False)
    op.create_index("ix_job_pending", "background_job", ["status", "next_run_at"], unique=False)
    op.create_table(
        "retrieval_trace",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("release_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_chunk_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("returned_chunk_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("scores_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("filter_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latency_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("failure_code", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_trace")),
    )
    op.create_index("ix_trace_created", "retrieval_trace", ["created_at"], unique=False)
    op.create_index(
        "ix_trace_request", "retrieval_trace", ["tenant_id", "request_id"], unique=False
    )
    op.create_table(
        "scene_space",
        sa.Column("hospital_id", sa.Text(), nullable=False),
        sa.Column("external_space_id", sa.Text(), nullable=False),
        sa.Column("active_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("row_version > 0", name=op.f("ck_scene_space_row_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_space")),
        sa.UniqueConstraint("id", "tenant_id", name=op.f("uq_scene_space_id_tenant_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "external_space_id",
            name=op.f("uq_scene_space_tenant_id_external_space_id"),
        ),
    )
    op.create_table(
        "source_asset",
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("source_locator", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_source_asset_sha256")),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_source_asset_nonnegative_size")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_asset")),
        sa.UniqueConstraint("id", "tenant_id", name=op.f("uq_source_asset_id_tenant_id")),
        sa.UniqueConstraint(
            "tenant_id", "storage_key", name=op.f("uq_source_asset_tenant_id_storage_key")
        ),
    )
    op.create_table(
        "knowledge_base",
        sa.Column("scope_key", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("hospital_id", sa.Text(), nullable=True),
        sa.Column("space_id", sa.Uuid(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("active_release_id", sa.Uuid(), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code <> 'scene_kb' OR space_id IS NOT NULL",
            name=op.f("ck_knowledge_base_scene_space_required"),
        ),
        sa.CheckConstraint(
            "code IN ('rehab_kb','scene_kb','clinical_kb','device_kb','hospital_kb','sop_kb')",
            name=op.f("ck_knowledge_base_known_code"),
        ),
        sa.CheckConstraint("length(scope_key) > 0", name=op.f("ck_knowledge_base_scope_nonempty")),
        sa.CheckConstraint("row_version > 0", name=op.f("ck_knowledge_base_row_version_positive")),
        sa.ForeignKeyConstraint(
            ["space_id", "tenant_id"],
            ["scene_space.id", "scene_space.tenant_id"],
            name=op.f("fk_knowledge_base_space_id_tenant_id_scene_space"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_base")),
        sa.UniqueConstraint("id", "tenant_id", name=op.f("uq_knowledge_base_id_tenant_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "scope_key",
            "code",
            name=op.f("uq_knowledge_base_tenant_id_scope_key_code"),
        ),
    )
    op.create_table(
        "scene_snapshot",
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("base_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("upstream_catalog_version", sa.Integer(), nullable=False),
        sa.Column("source_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_scene_snapshot_source_hash")
        ),
        sa.CheckConstraint(
            "status <> 'published' OR published_at IS NOT NULL",
            name=op.f("ck_scene_snapshot_publish_time"),
        ),
        sa.CheckConstraint(
            "status IN ('draft','approved','published','retired')",
            name=op.f("ck_scene_snapshot_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('approved','published') OR "
            "(reviewed_by IS NOT NULL AND length(trim(reviewed_by)) > 0)",
            name=op.f("ck_scene_snapshot_reviewer"),
        ),
        sa.CheckConstraint(
            "revision > 0 AND upstream_catalog_version >= 0",
            name=op.f("ck_scene_snapshot_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["base_snapshot_id", "space_id"],
            ["scene_snapshot.id", "scene_snapshot.space_id"],
            name=op.f("fk_scene_snapshot_base_snapshot_id_space_id_scene_snapshot"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id", "tenant_id"],
            ["scene_space.id", "scene_space.tenant_id"],
            name=op.f("fk_scene_snapshot_space_id_tenant_id_scene_space"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_snapshot")),
        sa.UniqueConstraint("id", "space_id", name=op.f("uq_scene_snapshot_id_space_id")),
        sa.UniqueConstraint("id", "tenant_id", name=op.f("uq_scene_snapshot_id_tenant_id")),
        sa.UniqueConstraint(
            "id",
            "upstream_catalog_version",
            name=op.f("uq_scene_snapshot_id_upstream_catalog_version"),
        ),
        sa.UniqueConstraint(
            "space_id", "revision", name=op.f("uq_scene_snapshot_space_id_revision")
        ),
    )
    op.create_table(
        "kb_release",
        sa.Column("kb_id", sa.Uuid(), nullable=False),
        sa.Column("release_no", sa.Integer(), nullable=False),
        sa.Column("base_release_id", sa.Uuid(), nullable=True),
        sa.Column("scene_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("manifest_hash", sa.Text(), nullable=False),
        sa.Column("collection_name", sa.Text(), nullable=False),
        sa.Column("embedding_revision", sa.Text(), nullable=False),
        sa.Column("reranker_revision", sa.Text(), nullable=False),
        sa.Column("chunker_version", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("requested_effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "manifest_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_kb_release_manifest_hash")
        ),
        sa.CheckConstraint(
            "status <> 'active' OR activated_at IS NOT NULL",
            name=op.f("ck_kb_release_activation_time"),
        ),
        sa.CheckConstraint(
            "status IN ('queued','building','ready','active','retired','failed','conflict')",
            name=op.f("ck_kb_release_status"),
        ),
        sa.CheckConstraint("release_no > 0", name=op.f("ck_kb_release_positive_release")),
        sa.ForeignKeyConstraint(
            ["base_release_id", "kb_id"],
            ["kb_release.id", "kb_release.kb_id"],
            name=op.f("fk_kb_release_base_release_id_kb_id_kb_release"),
        ),
        sa.ForeignKeyConstraint(
            ["kb_id", "tenant_id"],
            ["knowledge_base.id", "knowledge_base.tenant_id"],
            name=op.f("fk_kb_release_kb_id_tenant_id_knowledge_base"),
        ),
        sa.ForeignKeyConstraint(
            ["scene_snapshot_id", "tenant_id"],
            ["scene_snapshot.id", "scene_snapshot.tenant_id"],
            name=op.f("fk_kb_release_scene_snapshot_id_tenant_id_scene_snapshot"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_release")),
        sa.UniqueConstraint("collection_name", name=op.f("uq_kb_release_collection_name")),
        sa.UniqueConstraint(
            "id", "kb_id", "tenant_id", name=op.f("uq_kb_release_id_kb_id_tenant_id")
        ),
        sa.UniqueConstraint("id", "kb_id", name=op.f("uq_kb_release_id_kb_id")),
        sa.UniqueConstraint("kb_id", "release_no", name=op.f("uq_kb_release_kb_id_release_no")),
    )
    op.create_table(
        "scene_node",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("parent_node_id", sa.Text(), nullable=True),
        sa.Column("node_type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("zone", sa.Text(), nullable=True),
        sa.Column(
            "allowed_roles",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("source_locator", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "node_type IN ('hospital','floor','zone','room')", name=op.f("ck_scene_node_node_type")
        ),
        sa.CheckConstraint(
            "parent_node_id IS NULL OR parent_node_id <> node_id",
            name=op.f("ck_scene_node_not_own_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "parent_node_id"],
            ["scene_node.snapshot_id", "scene_node.node_id"],
            name=op.f("fk_scene_node_snapshot_id_parent_node_id_scene_node"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["scene_snapshot.id"],
            name=op.f("fk_scene_node_snapshot_id_scene_snapshot"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "node_id", name=op.f("pk_scene_node")),
    )
    op.create_table(
        "source_document",
        sa.Column("kb_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("source_instance_id", sa.Text(), nullable=False),
        sa.Column("external_key", sa.Text(), nullable=False),
        sa.Column("external_dataset_id", sa.Text(), nullable=True),
        sa.Column("external_document_id", sa.Text(), nullable=True),
        sa.Column("lifecycle", sa.Text(), server_default="active", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle IN ('active','archived')", name=op.f("ck_source_document_lifecycle")
        ),
        sa.ForeignKeyConstraint(
            ["kb_id", "tenant_id"],
            ["knowledge_base.id", "knowledge_base.tenant_id"],
            name=op.f("fk_source_document_kb_id_tenant_id_knowledge_base"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_document")),
        sa.UniqueConstraint(
            "id", "kb_id", "tenant_id", name=op.f("uq_source_document_id_kb_id_tenant_id")
        ),
        sa.UniqueConstraint(
            "kb_id",
            "source_instance_id",
            "external_key",
            name=op.f("uq_source_document_kb_id_source_instance_id_external_key"),
        ),
    )
    op.create_index(
        "ix_document_kb_lifecycle", "source_document", ["kb_id", "lifecycle"], unique=False
    )
    op.create_table(
        "document_version",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("kb_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("upstream_version", sa.Text(), nullable=True),
        sa.Column("original_asset_id", sa.Uuid(), nullable=True),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("metadata_hash", sa.Text(), nullable=False),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "audiences",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("review_status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "audiences <@ ARRAY['patient','doctor','internal']::text[]",
            name=op.f("ck_document_version_audiences"),
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_document_version_content_hash")
        ),
        sa.CheckConstraint(
            "metadata_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_document_version_metadata_hash")
        ),
        sa.CheckConstraint(
            "review_status <> 'approved' OR (reviewed_by IS NOT NULL "
            "AND length(trim(reviewed_by)) > 0 AND reviewed_at IS NOT NULL "
            "AND cardinality(audiences) > 0)",
            name=op.f("ck_document_version_approval_provenance"),
        ),
        sa.CheckConstraint(
            "review_status IN ('draft','pending','approved','rejected')",
            name=op.f("ck_document_version_review_status"),
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > effective_at",
            name=op.f("ck_document_version_valid_window"),
        ),
        sa.CheckConstraint(
            "revision > 0 AND row_version > 0", name=op.f("ck_document_version_positive_versions")
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "kb_id", "tenant_id"],
            ["source_document.id", "source_document.kb_id", "source_document.tenant_id"],
            name=op.f("fk_document_version_document_id_kb_id_tenant_id_source_document"),
        ),
        sa.ForeignKeyConstraint(
            ["original_asset_id", "tenant_id"],
            ["source_asset.id", "source_asset.tenant_id"],
            name=op.f("fk_document_version_original_asset_id_tenant_id_source_asset"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_version")),
        sa.UniqueConstraint(
            "document_id", "revision", name=op.f("uq_document_version_document_id_revision")
        ),
        sa.UniqueConstraint(
            "id",
            "document_id",
            "kb_id",
            "tenant_id",
            name=op.f("uq_document_version_id_document_id_kb_id_tenant_id"),
        ),
        sa.UniqueConstraint("id", "tenant_id", name=op.f("uq_document_version_id_tenant_id")),
    )
    op.create_index(
        "ix_version_document_revision",
        "document_version",
        ["document_id", "revision"],
        unique=False,
    )
    op.create_table(
        "scene_edge",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("edge_id", sa.Text(), nullable=False),
        sa.Column("from_node_id", sa.Text(), nullable=False),
        sa.Column("to_node_id", sa.Text(), nullable=False),
        sa.Column("edge_type", sa.Text(), nullable=False),
        sa.Column("cost_seconds", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column(
            "allowed_roles",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "edge_type IN ('walk','teleport','elevator')", name=op.f("ck_scene_edge_edge_type")
        ),
        sa.CheckConstraint("cost_seconds >= 0", name=op.f("ck_scene_edge_nonnegative_cost")),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "from_node_id"],
            ["scene_node.snapshot_id", "scene_node.node_id"],
            name=op.f("fk_scene_edge_snapshot_id_from_node_id_scene_node"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "to_node_id"],
            ["scene_node.snapshot_id", "scene_node.node_id"],
            name=op.f("fk_scene_edge_snapshot_id_to_node_id_scene_node"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "edge_id", name=op.f("pk_scene_edge")),
    )
    op.create_index("ix_edge_outgoing", "scene_edge", ["snapshot_id", "from_node_id"], unique=False)
    op.create_table(
        "scene_object",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Text(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("object_type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "capabilities_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_locator", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "node_id"],
            ["scene_node.snapshot_id", "scene_node.node_id"],
            name=op.f("fk_scene_object_snapshot_id_node_id_scene_node"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "object_id", name=op.f("pk_scene_object")),
        sa.UniqueConstraint(
            "snapshot_id",
            "object_id",
            "node_id",
            name=op.f("uq_scene_object_snapshot_id_object_id_node_id"),
        ),
    )
    op.create_index("ix_object_node", "scene_object", ["snapshot_id", "node_id"], unique=False)
    op.create_table(
        "document_chunk",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("chunker_version", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("parent_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("section_path", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("scene_node_id", sa.Text(), nullable=True),
        sa.Column("scene_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_document_chunk_content_hash")
        ),
        sa.CheckConstraint(
            "(scene_snapshot_id IS NULL) = (scene_node_id IS NULL)",
            name=op.f("ck_document_chunk_scene_anchor_pair"),
        ),
        sa.CheckConstraint(
            "ordinal >= 0 AND token_count >= 0", name=op.f("ck_document_chunk_nonnegative_counts")
        ),
        sa.CheckConstraint(
            "parent_chunk_id IS NULL OR parent_chunk_id <> id",
            name=op.f("ck_document_chunk_not_own_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_chunk_id", "version_id", "chunker_version"],
            ["document_chunk.id", "document_chunk.version_id", "document_chunk.chunker_version"],
            name=op.f(
                "fk_document_chunk_parent_chunk_id_version_id_chunker_version_document_chunk"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["scene_snapshot_id", "scene_node_id"],
            ["scene_node.snapshot_id", "scene_node.node_id"],
            name=op.f("fk_document_chunk_scene_snapshot_id_scene_node_id_scene_node"),
        ),
        sa.ForeignKeyConstraint(
            ["scene_snapshot_id", "tenant_id"],
            ["scene_snapshot.id", "scene_snapshot.tenant_id"],
            name=op.f("fk_document_chunk_scene_snapshot_id_tenant_id_scene_snapshot"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id", "tenant_id"],
            ["document_version.id", "document_version.tenant_id"],
            name=op.f("fk_document_chunk_version_id_tenant_id_document_version"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunk")),
        sa.UniqueConstraint(
            "id",
            "version_id",
            "chunker_version",
            name=op.f("uq_document_chunk_id_version_id_chunker_version"),
        ),
        sa.UniqueConstraint(
            "version_id",
            "chunker_version",
            "ordinal",
            name=op.f("uq_document_chunk_version_id_chunker_version_ordinal"),
        ),
    )
    op.create_table(
        "kb_release_document",
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("kb_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "kb_id", "tenant_id"],
            ["kb_release.id", "kb_release.kb_id", "kb_release.tenant_id"],
            name=op.f("fk_kb_release_document_release_id_kb_id_tenant_id_kb_release"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id", "document_id", "kb_id", "tenant_id"],
            [
                "document_version.id",
                "document_version.document_id",
                "document_version.kb_id",
                "document_version.tenant_id",
            ],
            name=op.f(
                "fk_kb_release_document_version_id_document_id_kb_id_tenant_id_document_version"
            ),
        ),
        sa.PrimaryKeyConstraint("release_id", "document_id", name=op.f("pk_kb_release_document")),
    )
    op.create_table(
        "scene_action",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Text(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("object_id", sa.Text(), nullable=True),
        sa.Column("action_key", sa.Text(), nullable=False),
        sa.Column("permission_level", sa.Text(), server_default="confirm", nullable=False),
        sa.Column("command_type", sa.Text(), nullable=False),
        sa.Column("command_index", sa.Integer(), nullable=False),
        sa.Column("upstream_catalog_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "command_type IN ('Telepor','ScenePoint','ClickPoint','GamePoint')",
            name=op.f("ck_scene_action_command_type"),
        ),
        sa.CheckConstraint(
            "permission_level IN ('free','confirm','professional','forbidden')",
            name=op.f("ck_scene_action_permission"),
        ),
        sa.CheckConstraint("command_index >= 0", name=op.f("ck_scene_action_nonnegative_command")),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "node_id"],
            ["scene_node.snapshot_id", "scene_node.node_id"],
            name=op.f("fk_scene_action_snapshot_id_node_id_scene_node"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "object_id", "node_id"],
            ["scene_object.snapshot_id", "scene_object.object_id", "scene_object.node_id"],
            name=op.f("fk_scene_action_snapshot_id_object_id_node_id_scene_object"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "upstream_catalog_version"],
            ["scene_snapshot.id", "scene_snapshot.upstream_catalog_version"],
            name=op.f("fk_scene_action_snapshot_id_upstream_catalog_version_scene_snapshot"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "action_id", name=op.f("pk_scene_action")),
    )
    op.create_table(
        "scene_service",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("service_code", sa.Text(), nullable=False),
        sa.Column("object_id", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "node_id"],
            ["scene_node.snapshot_id", "scene_node.node_id"],
            name=op.f("fk_scene_service_snapshot_id_node_id_scene_node"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "object_id", "node_id"],
            ["scene_object.snapshot_id", "scene_object.object_id", "scene_object.node_id"],
            name=op.f("fk_scene_service_snapshot_id_object_id_node_id_scene_object"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_service")),
        sa.UniqueConstraint(
            "snapshot_id",
            "node_id",
            "service_code",
            "object_id",
            name=op.f("uq_scene_service_snapshot_id_node_id_service_code_object_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_service_lookup",
        "scene_service",
        ["snapshot_id", "service_code", "node_id"],
        unique=False,
    )
    # Current pointers close cycles and must be added after their target tables.
    op.create_foreign_key(
        "fk_space_active_snapshot",
        "scene_space",
        "scene_snapshot",
        ["active_snapshot_id", "id"],
        ["id", "space_id"],
    )
    op.create_foreign_key(
        "fk_kb_active_release",
        "knowledge_base",
        "kb_release",
        ["active_release_id", "id"],
        ["id", "kb_id"],
    )


def downgrade() -> None:
    op.drop_constraint("fk_kb_active_release", "knowledge_base", type_="foreignkey")
    op.drop_constraint("fk_space_active_snapshot", "scene_space", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_service_lookup", table_name="scene_service")
    op.drop_table("scene_service")
    op.drop_table("scene_action")
    op.drop_table("kb_release_document")
    op.drop_table("document_chunk")
    op.drop_index("ix_object_node", table_name="scene_object")
    op.drop_table("scene_object")
    op.drop_index("ix_edge_outgoing", table_name="scene_edge")
    op.drop_table("scene_edge")
    op.drop_index("ix_version_document_revision", table_name="document_version")
    op.drop_table("document_version")
    op.drop_index("ix_document_kb_lifecycle", table_name="source_document")
    op.drop_table("source_document")
    op.drop_table("scene_node")
    op.drop_table("kb_release")
    op.drop_table("scene_snapshot")
    op.drop_table("knowledge_base")
    op.drop_table("source_asset")
    op.drop_table("scene_space")
    op.drop_index("ix_trace_request", table_name="retrieval_trace")
    op.drop_index("ix_trace_created", table_name="retrieval_trace")
    op.drop_table("retrieval_trace")
    op.drop_index("ix_job_pending", table_name="background_job")
    op.drop_index("ix_job_expired", table_name="background_job")
    op.drop_table("background_job")
    op.drop_index("ix_audit_entity", table_name="audit_event")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
